package modelo;
// Generated 11-may-2018 13:18:58 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Libros generated by hbm2java
 */

@Entity
@Table(name="Libros")
public class Libros implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	@Column(name="titulo")
	private String titulo;
	@Column(name="autor")
	private String autor;
	@OneToMany(mappedBy="libros")
	private Set prestamoses = new HashSet(0);

	public Libros() {
	}

	public Libros(String titulo, String autor) {
		this.titulo = titulo;
		this.autor = autor;
	}

	public Libros(String titulo, String autor, Set prestamoses) {
		this.titulo = titulo;
		this.autor = autor;
		//this.prestamoses = prestamoses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getAutor() {
		return this.autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	public Set getPrestamoses() {
		return this.prestamoses;
	}

	public void setPrestamoses(Set prestamoses) {
		this.prestamoses = prestamoses;
	}

}
