package modelo;
// Generated 11-may-2018 13:18:58 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * Prestamos generated by hbm2java
 */
public class Prestamos implements java.io.Serializable {

	private Integer id;
	private Libros libros;
	private Usuarios usuarios;
	private Date fechaPrestamo;
	private Date fechaLimite;
	private boolean entregado;

	public Prestamos() {
	}

	public Prestamos(Libros libros, Usuarios usuarios, Date fechaPrestamo, Date fechaLimite, boolean entregado) {
		this.libros = libros;
		this.usuarios = usuarios;
		this.fechaPrestamo = fechaPrestamo;
		this.fechaLimite = fechaLimite;
		this.entregado = entregado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Libros getLibros() {
		return this.libros;
	}

	public void setLibros(Libros libros) {
		this.libros = libros;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Date getFechaPrestamo() {
		return this.fechaPrestamo;
	}

	public void setFechaPrestamo(Date fechaPrestamo) {
		this.fechaPrestamo = fechaPrestamo;
	}

	public Date getFechaLimite() {
		return this.fechaLimite;
	}

	public void setFechaLimite(Date fechaLimite) {
		this.fechaLimite = fechaLimite;
	}

	public boolean isEntregado() {
		return this.entregado;
	}

	public void setEntregado(boolean entregado) {
		this.entregado = entregado;
	}

}
