package modelo;
// Generated 11-may-2018 13:18:58 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String apellido;
	private int edad;
	private String dni;
	private Date fechaNacimiento;
	private String contrasena;
	private String rol;
	private Set prestamoses = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(String nombre, String apellido, int edad, String contrasena, String rol) {
		this.nombre = nombre;
		this.apellido = apellido;
		this.edad = edad;
		this.contrasena = contrasena;
		this.rol = rol;
	}

	public Usuarios(String nombre, String apellido, int edad, String dni, Date fechaNacimiento, String contrasena,
			String rol, Set prestamoses) {
		this.nombre = nombre;
		this.apellido = apellido;
		this.edad = edad;
		this.dni = dni;
		this.fechaNacimiento = fechaNacimiento;
		this.contrasena = contrasena;
		this.rol = rol;
		this.prestamoses = prestamoses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	public Set getPrestamoses() {
		return this.prestamoses;
	}

	public void setPrestamoses(Set prestamoses) {
		this.prestamoses = prestamoses;
	}

}
